# Generated by Django 4.2.2 on 2023-06-28 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("appadmin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminmodel",
            name="apppic",
            field=models.ImageField(default="Images/Noimg.jpg", upload_to="Images/"),
        ),
        migrations.AddField(
            model_name="adminmodel",
            name="points",
            field=models.CharField(max_length=10),
            preserve_default=False,
        ),
    ]
